=== tinatsai0122/xml/Ex01/Ex01.dtd
<!ELEMENT books (serie*)>
<!ELEMENT serie (book*)>
<!ATTLIST serie name CDATA #REQUIRED>
<!ATTLIST book tome CDATA #REQUIRED>
<!ELEMENT book (titre, auteur, genres, datePublication)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (nom, prenom+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT genres (genre*)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT datePublication (#PCDATA)>
<!ATTLIST datePublication forma CDATA #FIXED "dd/mm/yyyy">

=== tinatsai0122/xml/Ex01/Ex01.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE books SYSTEM "./Ex01.dtd">

<books>
    <serie name="Harry Potter">
        <book tome="1">
            <titre>Harry Potter: Philosopher's Stone</titre>
            <auteur>
                <nom>Rowling</nom>
                <prenom>Joanne</prenom>
            </auteur>
            <genres>
                <genre>Fantastique</genre>
                <genre>Jeunesse</genre>
                <genre>Roman</genre>
                <genre>Fiction</genre>
            </genres>
            <datePublication forma="dd/mm/yyyy">26/06/1997
            </datePublication>
        </book>
        <book tome="2">
            <titre>Harry Potter: Chamber of Secrets</titre>
            <auteur>
                <nom>Rowling</nom>
                <prenom>Joanne</prenom>
            </auteur>
            <genres>
                <genre>Fantastique</genre>
                <genre>Jeunesse</genre>
                <genre>Roman</genre>
                <genre>Fiction</genre>
            </genres>
            <datePublication forma="dd/mm/yyyy">02/07/1998
            </datePublication>
        </book>
    </serie>
</books>
