=== tinatsai0122/xml/Ex05/Exo05.xsd
<?xml version="1.1" encoding="UTF-8" standalone="yes"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:complexType name="T_Personne">
        <xsd:sequence>
            <xsd:element ref="nom"/>
            <xsd:element ref="prénom"/>
            <xsd:element ref="date-naissance"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="formation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nom"/>
                <xsd:element ref="eleves"/>
                <xsd:element ref="matières"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>    
    <xsd:element name="nom" type="xsd:string"/>
    <xsd:element name="prénom" type="xsd:string"/>
    <xsd:element name="date-naissance" type="xsd:date"/>
    <xsd:element name="eleves">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="eleve" maxOccurs="14"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="eleve" type="T_Personne"/>
    <xsd:element name="matières">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="cours" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="cours">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nom"/>
                <xsd:element ref="professeur" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="professeur" type="T_Personne"/>
</xsd:schema>

=== tinatsai0122/xml/Ex05/Exo05.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>

<formation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./Exo05.xsd">
    <nom>WAD23</nom>
    <eleves>
        <eleve>
            <nom>Bouharat</nom>
            <prénom>Najoua</prénom>
            <date-naissance>1982-10-04</date-naissance>
        </eleve>
        <eleve>
            <nom>Rottin</nom>
            <prénom>Elena</prénom>
            <date-naissance>1979-04-23</date-naissance>
        </eleve>
        <eleve>
            <nom>Cardu</nom>
            <prénom>Emanuela</prénom>
            <date-naissance>1977-04-19</date-naissance>
        </eleve>
    </eleves>
    <matières>
        <cours>
            <nom>C#</nom>
            <professeur>
                <nom>Claes</nom>
                <prénom>Alexandre</prénom>
                <date-naissance>1987-05-01</date-naissance>
            </professeur>
        </cours>
        <cours>
            <nom>XML</nom>
            <professeur>
                <nom>Legrain</nom>
                <prénom>Samuel</prénom>
                <date-naissance>1987-09-27</date-naissance>
            </professeur>
        </cours>
    </matières>
</formation>
