=== tinatsai0122/xml/ExExtra01/bibliographie.dtd
<!ELEMENT bibliographie (livre*, article*)>

<!ELEMENT livre (titre, auteur, infoEdition, avis*)>
<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre tome CDATA #IMPLIED>
<!ATTLIST titre nbPage CDATA #IMPLIED>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT infoEdition (editeur, lieuEdition, lieuImpression,isbn)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lieuEdition (#PCDATA)>
<!ELEMENT lieuImpression (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT avis (nom, commentaire)>
<!ATTLIST avis note (0|1|2|3|4|5) #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT commentaire (#PCDATA)>
<!ELEMENT article (titre, auteur, reference, avis*)>
<!ELEMENT reference (nomJournal, volume, anneePublication, numeroJournal)>
<!ELEMENT nomJournal (#PCDATA)>
<!ELEMENT nbPage (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT anneePublication (#PCDATA)>
<!ELEMENT numeroJournal (#PCDATA)>

=== tinatsai0122/xml/ExExtra01/bibliographie.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE bibliographie SYSTEM "./bibliographie.dtd">

<bibliographie>
    <livre>
        <titre tome="1" nbPage="235">Littérature</titre>
        <auteur>GIRAUDOUX Jean</auteur>
        <infoEdition>
            <editeur>BIGOT Michel</editeur>
            <lieuEdition>Paris</lieuEdition>
            <lieuImpression>Paris</lieuImpression> 
            <isbn>978-3-16-148410-0</isbn>        
        </infoEdition>
        <avis note="5">
            <nom>Lily</nom>
            <commentaire>Très bon livre</commentaire>
        </avis>
        <avis note="4">
            <nom>John</nom>
            <commentaire>Bon livre</commentaire>
        </avis>
    </livre>
    <article>
        <titre>Semi-conducteurs</titre>
        <auteur>BOK Julien</auteur>
        <reference>
            <nomJournal>Encyclopaedia Universalis</nomJournal>
            <volume>2</volume>
            <anneePublication>1994</anneePublication>
            <numeroJournal>p. 879-883</numeroJournal>
        </reference>
        <avis note="4">
            <nom>Jolie</nom>
            <commentaire>Très bon article</commentaire>
        </avis>
        <avis note="5">
            <nom>Chris</nom>
            <commentaire>Bon article</commentaire>
        </avis>
    </article>
</bibliographie>
