=== tinatsai0122/xml/epreuve/Exo01.dtd
<!ELEMENT composition (auteur,date_creation,fleuriste?,composants)>
<!ATTLIST composition id ID #REQUIRED>
<!ELEMENT auteur (firstname,lastname?)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT date_creation (#PCDATA)>
<!ATTLIST date_creation DATETIME CDATA #IMPLIED>
<!ELEMENT fleuriste (lieu?,ville?)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT composants (vase,fleurs)>
<!ELEMENT vase (matiere,taille)>
<!ELEMENT matiere (#PCDATA)>
<!ELEMENT taille (profondeur, hauteur)>
<!ATTLIST taille unit (cm|in|ft) "cm">
<!ELEMENT profondeur (#PCDATA)>
<!ELEMENT hauteur (#PCDATA)>
<!ELEMENT fleurs (nature,item+)>
<!ELEMENT nature (#PCDATA)>
<!ELEMENT item (#PCDATA)>

=== tinatsai0122/xml/epreuve/Exo01.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>

<!DOCTYPE composition SYSTEM "./Exo01.dtd"> 

<composition id="bouquet_01">
    <auteur>
        <firstname>Floristore</firstname>
        <lastname/>
    </auteur>
    <date_creation>2001-02-29</date_creation>
    <fleuriste>
        <ville>Paris</ville>
    </fleuriste>
    <composants>
        <vase>
            <matiere>Porcelaine</matiere>
            <taille unit="cm">
                <profondeur>50</profondeur>
                <hauteur>70</hauteur>
            </taille>
        </vase>
        <fleurs>
            <nature>Europ√©enne</nature>
            <item>Tulipe</item>
            <item>Glaieul</item>
            <item>Marguerite</item>
        </fleurs>
    </composants>
</composition>
