<?xml version="1.1" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE scores [
    <!ELEMENT scores (score+, total)>
    <!ELEMENT score (game, point, point+)>
    <!ELEMENT game (Uno|Dames|Echec)>
    <!ATTLIST game nb-player (2|3|4|5|6) #REQUIRED>
    <!ELEMENT Uno EMPTY>
    <!ELEMENT Dames EMPTY>
    <!ELEMENT Echec EMPTY>
    <!ELEMENT point (#PCDATA)>
    <!ATTLIST point name CDATA #REQUIRED>
    <!ATTLIST point id ID #REQUIRED>
    <!ATTLIST point total-ref IDREF #IMPLIED>
    <!ELEMENT total (point, point+)>
]>

<scores>
    <score>
        <game nb-player="4">
            <Uno />
        </game>
        <point id="score_01_aude" total-ref="total_aude" name="Aude">255</point>
        <point id="score_01_michael" total-ref="total_michael" name="Michael">249</point>
        <point id="score_01_thierry" total-ref="total_thierry" name="Thierry">125</point>
        <point id="score_01_sam" total-ref="total_sam" name="Samuel">0</point>
    </score>
    <score>
        <game nb-player="4">
            <Dames />
        </game>
        <point id="score_02_aude" total-ref="total_aude" name="Aude">42</point>
        <point id="score_02_michael" total-ref="total_michael" name="Michael">13</point>
        <point id="score_02_thierry" total-ref="total_thierry" name="Thierry">2</point>
        <point id="score_02_sam" total-ref="total_sam" name="Samuel">255</point>
    </score>
    <total>
        <point id="total_aude" name="Aude">297</point>
        <point id="total_michael" name="Michael">262</point>
        <point id="total_thierry" name="Thierry">127</point>
        <point id="total_sam" name="Samuel">255</point>
    </total>
</scores>